version: '3.3'

services:

  onlyoffice-docs:
    image: onlyoffice/documentserver:latest  #latest-arm64 (para Raspberry Pi)
    container_name: onlyoffice-docs
    restart: unless-stopped
    stdin_open: true
    tty: true    
    ports:
      - '8500:80'
      - '8543:443'
    volumes:
      - ./onlyoffice/data:/var/www/onlyoffice/Data   
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=my_secret
      - JWT_HEADER=Authorization
      - JWT_IN_BODY=true
    stop_grace_period: 60s


